# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6cdb2c4be46d7d056c6767e65505de1617a293c604eacb2b6c8b57faa490a9da29669430d86ad8b5f2e23bda928a18de2cebc21d076049cfd8ceb07a53b3c85

test:
  secret_key_base: 757b0c3fc563f5439c1f1b57eb496238c02c7d2729e98db1fb20051aa370cdec561099c9d8e61f3ee375c662bb694c85ecb455b328573a0c1274dc1fbf974f61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
